# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TRPropertyCode' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TRPropertyCode

  target 'TRPropertyCodeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TRPropertyCodeUITests' do
    inherit! :search_paths
    # Pods for testing
  end
  
  pod 'AFNetworking', '~> 3.1.0'

end
